replicaCount: 1

image:
  repository: sergeygav/hello-world
  tag: latest

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30001

resources:
  requests:
    cpu: "50m"
    memory: "32Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"